name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Node.js (if using JS/CSS build tools like Webpack, Gulp, etc.)
        uses: actions/setup-node@v2
        with:
          node-version: '14'
        
      - name: Install dependencies
        run: |
          npm install
          
      - name: Build project (optional: only if you have a build step like Webpack)
        run: |
          npm run build
          
      - name: Deploy to GitHub Pages (optional)
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: build
